---
###############################################################################
# Config
###############################################################################
# Server will automatically populate any required .ini file on initial shutdown
# if it does not exist on service start. Any pre-existing .ini file will not be
# touched and assumed correct.
#
# Only set configuration files if they are defined.
#
# Filetree returns a dict (instead of a list of dict) for one element. Use
# flatten to convert the result to a list if needed.
#
# Reference:
# * https://satisfactory.wiki.gg/wiki/Dedicated_servers/Configuration_files

- name: 'Config | filetree | deploy managed files'
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ satisfactory__cfg._ini_dir ~ "/" ~ item.path }}'
    owner: '{{ steam__ctx._user }}'
    group: '{{ steam__ctx._group }}'
    mode: '0664'  # Game enforced.
  loop: '{{ query("community.general.filetree", satisfactory__cfg._cfg_dir) }}'
  loop_control:
    label: '{{ item.path }}'
  when: item.state == 'file'
  register: satisfactory__local

- name: 'Config | filesystem | query remote files'
  ansible.builtin.find:
    paths: '{{ satisfactory__cfg._ini_dir }}'
    file_type: 'file'
    recurse: true
  register: satisfactory__remote

- name: 'Config | filesystem | remove unmanaged files'
  ansible.builtin.file:
    path: '{{ item.path }}'
    state: 'absent'
  loop: '{{ satisfactory__remote.files }}'
  loop_control:
    label: '{{ item.path }}'
  when: >
    item.path not in satisfactory__local.results | map(attribute='dest') | list
