---
###############################################################################
# Install
###############################################################################
# Find current install and branch, and update save location mapping based on
# steam user home directory. Updates will occur if:
# * Not installed.
# * Wrong branch.
# * Force updates flagged.
#
# Reference:
# * https://satisfactory.wiki.gg/wiki/Dedicated_servers#SteamCMD

- name: 'Install | steamcmd'
  ansible.builtin.import_role:
    name: 'r_pufky.game.steam'
  vars:
    steam_flg_update: false
    steam_flg_container: '{{ satisfactory_flg_container }}'
    steam_flg_cdn: '{{ satisfactory_flg_cdn }}'

- name: 'Install | filesystem | find current installation'
  ansible.builtin.stat:
    path: '{{ satisfactory___app._bin }}'
  register: satisfactory__installed

- name: 'Install | filesystem | query installed branch'
  when: satisfactory__installed.stat.exists
  ansible.builtin.find:
    paths: '{{ satisfactory___app._manifest | dirname }}'
    patterns: '{{ satisfactory___app._manifest | basename }}'
    file_type: 'file'
    read_whole_file: true
    contains: '(?m:UserConfig"\s*{\s*"BetaKey"\s*"public)'
    recurse: false
  register: satisfactory__installed_branch
  changed_when: false

# Default to 'public' if not branch found.
- name: 'Install | fact | set install state'
  ansible.builtin.set_fact:
    satisfactory__cfg: "{{ satisfactory__cfg | r_pufky.data.v3(

        _is_installed=satisfactory__installed.stat.exists,
        _installed_branch=(
            'public'
            if satisfactory__installed_branch.matched | default(1) > 0 else
            'experimental'
        ),
        _save_d=(
          steam__ctx._home ~ '/.config/Epic/FactoryGame/Saved/SaveGames'
        ),
      ) }}"

- name: '{{ "Install | filesystem | " ~ satisfactory___app._root_d }}'
  ansible.builtin.file:
    path: '{{ satisfactory___app._root_d }}'
    owner: '{{ steam__ctx._uid }}'
    group: '{{ steam__ctx._gid }}'
    mode: '0755'
    state: 'directory'

- name: '{{ "Install | filesystem | " ~ satisfactory__cfg._backup_d }}'
  when: satisfactory_flg_backup
  block:
    - name: '{{ "Install | filesystem | " ~ satisfactory__cfg._backup_d }}'
      ansible.builtin.file:
        path: '{{ satisfactory__cfg._backup_d }}'
        owner: '{{ steam__ctx._uid }}'
        group: '{{ steam__ctx._gid }}'
        mode: '0755'
        state: 'directory'
  rescue:
    - name: '{{ "Install ⛑ | filesystem | " ~ satisfactory__cfg._backup_d }}'
      ansible.builtin.file:
        path: '{{ satisfactory__cfg._backup_d }}'
        owner: '{{ steam__ctx._uid }}'
        group: '{{ steam__ctx._gid }}'
        mode: '0700'
        state: 'directory'
      become: true
      become_user: '{{ steam__ctx._user }}'

- name: '{{ "Install | filesystem | " ~ satisfactory___app._ini_d }}'
  ansible.builtin.file:
    path: '{{ satisfactory___app._ini_d }}'
    owner: '{{ steam__ctx._uid }}'
    group: '{{ steam__ctx._gid }}'
    mode: '0775'  # Game enforced.
    state: 'directory'

- name: '{{ "Install | filesystem | " ~ satisfactory___app._update_server }}'
  ansible.builtin.template:
    src: 'templates/update_server.j2'
    dest: '{{ satisfactory___app._update_server }}'
    owner: '{{ steam__ctx._uid }}'
    group: '{{ steam__ctx._gid }}'
    mode: '0755'

- name: 'Install | systemd | set satisfactory.service'
  ansible.builtin.template:
    src: 'systemd/satisfactory.service.j2'
    dest: '/etc/systemd/system/satisfactory.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
