---
###############################################################################
# Pre Execution Tasks
###############################################################################
# Only use data annotations in role after merging role, defaults, runtime data.
# Service may not exist if first install.

- name:
    'Prep | fact | force satisfactory_flg_container=true (deb_flg_container)'
  when: deb_flg_container | default(false)
  ansible.builtin.set_fact:
    satisfactory_flg_container: true

- name: 'Prep | fact | record start time'
  ansible.builtin.set_fact:
    satisfactory__srv: "{{ satisfactory___release | r_pufky.data.v3(

        _start=now(utc=True, fmt='%Y-%m-%dT%H%M%S'),

        _update_opts=satisfactory_srv_update_opts | join(' '),
        _launch_opts=satisfactory_srv_launch_opts | join(' '),
        _branch=satisfactory_srv_branch,
      ) }}"
    satisfactory__cfg: "{{ {} | r_pufky.data.v3(

        _cfg_d=satisfactory_cfg_d | regex_replace('\\/$', ''),
        _backup_d=satisfactory_cfg_backup_d | regex_replace('\\/$', ''),
        _backup_schedule=satisfactory_cfg_backup_schedule,
      ) }}"

- name: 'Prep | assert | config enabled and source defined'
  when: satisfactory_flg_config
  ansible.builtin.assert:
    quiet: true
    that:
      - satisfactory__cfg._cfg_d | length > 0
    fail_msg: |

      ✘ Config source not set.

      Config source enabled but no config source defined.

      satisfactory_flg_config: {{ satisfactory_flg_config }}
      satisfactory_cfg_d: {{ satisfactory__cfg._cfg_d }}

- name: 'Prep | systemd | stop satisfactory.service'
  ansible.builtin.systemd:
    name: 'satisfactory.service'
    state: 'stopped'
  failed_when: false
