---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Prepare | import role variables'
      ansible.builtin.include_vars:
        file: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/vars/main.yml"
          }}'

    # Just spot check a value in the list of files. Server automatically adds
    # and re-writes configuration on new builds and config values. All files
    # are deployed at the same time.
    - name: '{{
          "Verify | test | " ~ satisfactory___app._ini_d ~ "/Game.ini"
        }}'
      ansible.builtin.lineinfile:
        name: '{{ satisfactory___app._ini_d ~ "/Game.ini" }}'
        line: 'MaxPlayers=4'
        state: 'present'
      check_mode: true
      register: satisfactory__test
      failed_when: >
        satisfactory__test is changed or
        satisfactory__test is failed
